version: 2.1

workflows:
  test_workflow:
    jobs:
      - test
      - specwrk-single-node
      - specwrk-multi-node-prepare
      - specwrk-multi-node:
          requires:
            - specwrk-multi-node-prepare

jobs:
  test:
    docker:
      - image: cimg/ruby:3.4.4
    working_directory: ~/project
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "Gemfile" }}-{{ checksum "specwrk.gemspec" }}
            - v1-deps-{{ checksum "Gemfile" }}
            - v1-deps-

      - run:
          name: Install Gems
          command: |
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 2

      - save_cache:
          paths:
            - vendor/bundle
          key: v1-deps-{{ checksum "Gemfile" }}-{{ checksum "specwrk.gemspec" }}

      - run:
          name: Run RSpec
          command: bundle exec rspec

  specwrk-single-node:
    docker:
      - image: cimg/ruby:3.4.4
    working_directory: ~/project
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "Gemfile" }}-{{ checksum "specwrk.gemspec" }}
            - v1-deps-{{ checksum "Gemfile" }}
            - v1-deps-

      ## SPECWRK STEP ##
      - restore_cache:
          keys:
            - specwrk-{{ .Branch }}
            - specwrk-
      ## /SPECWRK STEP ##
          
      - run:
          name: Install Gems
          command: |
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 2

      - save_cache:
          paths:
            - vendor/bundle
          key: v1-deps-{{ checksum "Gemfile" }}-{{ checksum "specwrk.gemspec" }}

      ## SPECWRK STEP ##
      - run:
          name: Run tests via specwrk start
          command: bundle exec specwrk start --count 2 spec/
      ## /SPECWRK STEP ##
        
      ## SPECWRK STEP ##
      - save_cache:
          paths:
            - .specwrk/report.json
          key: specwrk-{{ .Branch }}
      ## /SPECWRK STEP ##
        
  specwrk-multi-node-prepare:
    docker:
      - image: cimg/ruby:3.4.4
    steps:
      - checkout

      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile" }}-{{ checksum "specwrk.gemspec" }}
            - gem-cache-{{ checksum "Gemfile" }}
            - gem-cache-

      - run:
          name: bundle install
          command: |
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 2

      - save_cache:
          paths:
            - vendor/bundle
          key: gem-cache-{{ checksum "Gemfile" }}-{{ checksum "specwrk.gemspec" }}

      ## SPECWRK STEP ##
      - run:
          name: Seed examples to specwrk server
          command: |
            bundle exec specwrk seed \
              --uri "$SPECWRK_URI" \
              --key "$SPECWRK_KEY" \
              --run "$CIRCLE_WORKFLOW_ID" \
              spec/

      ## /SPECWRK STEP ##

  specwrk-multi-node:
    parallelism: 2
    docker:
      - image: cimg/ruby:3.4.4
    working_directory: ~/project
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "Gemfile" }}-{{ checksum "specwrk.gemspec" }}
            - v1-deps-{{ checksum "Gemfile" }}
            - v1-deps-

      - run:
          name: Install Gems
          command: |
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 2

      - save_cache:
          paths:
            - vendor/bundle
          key: v1-deps-{{ checksum "Gemfile" }}-{{ checksum "specwrk.gemspec" }}

      ## SPECWRK STEP ##
      - run:
          name: Run tests via specwrk work
          command: |
            bundle exec specwrk work \
              --uri "$SPECWRK_URI" \
              --key "$SPECWRK_KEY" \
              --run "$CIRCLE_WORKFLOW_ID" \
              --count 2
      ## /SPECWRK STEP ##
