name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.4.2"
          - "3.3.0"
          - "3.2.0"
          - "3.1.0"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake

      - name: Run tests via specwrk start
        run: bundle exec specwrk start --count 2 spec/

      - name: Run tests via specwrk and individual commands
        run: |
          bundle exec specwrk serve --single-run 2>&1 &
          bundle exec specwrk seed spec
          bundle exec specwrk work --count 2
